### ISSUE TITLE
Invalid mod icon for ModMenu (Fabric 1.19.2)

### ISSUE THREAD

**Issue by teleheel** [Darkhax-Minecraft/What-The-Bucket#1]
When opening the `Mods` menu in Fabric 1.19.2 with ModMenu, the mod icon is set to the default question mark and the current error message is logged (with Not Enough Crashes installed):

```
[16:41:30] [Render thread/ERROR]: Invalid mod icon for icon source whatthebucket: assets/minecraft/textures/item/bucket.png
java.nio.file.NoSuchFileException: /assets/minecraft/textures/item/bucket.png
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
	at jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:861) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:749) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:261) ~[jdk.zipfs:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:34) ~[modmenu-4.1.2.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:145) ~[modmenu-4.1.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:96) ~[modmenu-4.1.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.render(ModListEntry.java:52) ~[modmenu-4.1.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.renderList(ModListWidget.java:226) ~[modmenu-4.1.2.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.render(EntryListWidget:232) ~[?:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:277) ~[modmenu-4.1.2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:881) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Darkhax** [comment]
Thanks for letting me know. This has been fixed for 1.18.2, 1.19.2, and 1.19.3
